=== LucaVacchetta/REST-WebService/schema/xml_components.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:simpleType name="functionalTypes">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ACL_FIREWALL"/>
			<xsd:enumeration value="END_HOST"/>
			<xsd:enumeration value="ANTISPAM"/>
			<xsd:enumeration value="CACHE"/>
			<xsd:enumeration value="DPI"/>
			<xsd:enumeration value="MAILCLIENT"/>
			<xsd:enumeration value="MAILSERVER"/>
			<xsd:enumeration value="NAT"/>
			<xsd:enumeration value="VPN_ACCESS"/>
			<xsd:enumeration value="VPN_EXIT"/>
			<xsd:enumeration value="WEBCLIENT"/>
			<xsd:enumeration value="WEBSERVER"/>
			<xsd:enumeration value="FIELDMODIFIER"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="policyTypes">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="reachability"/>
			<xsd:enumeration value="traversal"/>
			<xsd:enumeration value="isolation"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="graphs">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="graph" maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="uniqueGraph">
		   	<xsd:selector xpath="graph" /> 
		   	<xsd:field xpath="@id" /> 	
		</xsd:unique>
	</xsd:element>
	<xsd:element name="graph">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="node" maxOccurs="unbounded"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:long" use="optional"/>
		</xsd:complexType>
		<xsd:unique name="uniqueNodeId">
			<xsd:selector xpath="node"/>
			<xsd:field xpath="@id"/>
		</xsd:unique>
		<xsd:key name="keyNode">
			<xsd:selector xpath="node"/>
			<xsd:field xpath="@name"/>
		</xsd:key>
		<xsd:keyref name="keyRefNodeSrc" refer="keyNode">
			<xsd:selector xpath="node/neighbour"/>
			<xsd:field xpath="@name"/>
		</xsd:keyref>
	</xsd:element>
	<xsd:element name="node">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="neighbour" maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:long" use="optional"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
			<xsd:attribute name="functional_type" type="functionalTypes" use="required"/>
		</xsd:complexType>
		<xsd:unique name="uniqueNeighbourId">
			<xsd:selector xpath="neighbour"/>
			<xsd:field xpath="@id"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="neighbour">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:long" use="optional"/>
			<xsd:attribute name="name" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="paths">
 		<xsd:complexType>
 			<xsd:choice>
 				<xsd:element name="message" type="xsd:string"/>
 				<xsd:element name="path" type="xsd:string" maxOccurs="unbounded"/>
 			</xsd:choice>
 			<xsd:attribute name="source" type="xsd:string" use="required"/>
 			<xsd:attribute name="destination" type="xsd:string" use="required"/>
 			<xsd:attribute name="direction" type="xsd:string" use="required"/>
 		</xsd:complexType>
 	</xsd:element>
 	<xsd:element name="reachability">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="result" type="xsd:boolean"/>
			</xsd:sequence>
			<xsd:attribute name="source" type="xsd:string" use="required"/>
 			<xsd:attribute name="destination" type="xsd:string" use="required"/>
 			<xsd:attribute name="direction" type="xsd:string" use="required"/>
		</xsd:complexType> 	
 	</xsd:element>
  	<xsd:element name="policy">
 		<xsd:complexType>
 			<xsd:sequence>
				<xsd:element name="result" type="xsd:boolean"/>
			</xsd:sequence>
			<xsd:attribute name="source" type="xsd:string" use="required"/>
			<xsd:attribute name="middlebox" type="xsd:string" use="optional"/>
 			<xsd:attribute name="destination" type="xsd:string" use="required"/>
 			<xsd:attribute name="type" type="policyTypes" use="required"/>
 		</xsd:complexType>
 	</xsd:element>
</xsd:schema>

=== LucaVacchetta/REST-WebService/testcases/test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<graphs xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="../schema/xml_components.xsd">
	<graph>
		<node name="fw" functional_type="ACL_FIREWALL">
			<neighbour name="webserver1"/>
			<neighbour name="nat"/>
		</node>
		<node name="webserver1" functional_type="WEBSERVER">
			<neighbour name="sap3"/>
			<neighbour name="fw"/>
		</node>
		<node name="nat" functional_type="NAT">
			<neighbour name="sap1"/>
			<neighbour name="dpi"/>
			<neighbour name="fw"/>
		</node>
		<node name="dpi" functional_type="DPI">
			<neighbour name="sap2"/>
		</node>
		<node name="sap2" functional_type="END_HOST">
			<neighbour name="nat"/>
		</node>
		<node name="sap1" functional_type="END_HOST">
			<neighbour name="nat"/>
		</node>
		<node name="sap3" functional_type="END_HOST">
			<neighbour name="webserver1"/>
		</node>
	</graph>
</graphs>

=== LucaVacchetta/REST-WebService/testcases/test3.xml
<?xml version="1.0" encoding="UTF-8"?>
<graphs xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="../schema/xml_components.xsd">
	<graph>
		<node name="user1" functional_type="END_HOST">
			<neighbour name="nat"/>
		</node>
		<node name="nat" functional_type="NAT">
			<neighbour name="user1"/>
			<neighbour name="vpnaccess"/>
		</node>
		<node name="vpnaccess" functional_type="VPN_ACCESS">
			<neighbour name="nat"/>
			<neighbour name="fieldmodifier"/>
		</node>
		<node name="fieldmodifier" functional_type="FIELDMODIFIER">
			<neighbour name="vpnaccess"/>
			<neighbour name="vpnexit"/>
		</node>
		<node name="vpnexit" functional_type="VPN_EXIT">
			<neighbour name="fieldmodifier"/>
			<neighbour name="webserver"/>
		</node>
		<node name="webserver" functional_type="WEBSERVER">
			<neighbour name="vpnexit"/>
		</node>
	</graph>
</graphs>

=== LucaVacchetta/REST-WebService/testcases/test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<graphs xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="../schema/xml_components.xsd">
	<graph>
		<node name="user1" functional_type="END_HOST">
			<neighbour name="nat"/>
		</node>
		<node name="nat" functional_type="NAT">
			<neighbour name="dpi"/>
		</node>
		<node name="dpi" functional_type="DPI">
			<neighbour name="webserver"/>
		</node>
		<node name="webserver" functional_type="WEBSERVER"></node>
	</graph>
</graphs>
